### ISSUE TITLE
Php error during company creation

### ISSUE THREAD

**Issue by c0ldplasma** [TwakeApp/Twake#100]
**Describe the bug**
After setting up Twake with the provided docker-compose.yml I tried to create an account. After going through the steps for the account creation I get redirected to the page for creating a company as expected. After I enter the email adress for the company and click "Add" I get a php error: 

`NOTICE: PHP message: PHP Warning:  require(/twake-core/cache/Doctrine/Proxies/__CG__TwakeWorkspacesEntityWorkspace.php): failed to open stream: No such file or directory in /twake-core/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php on line 206"
`

At the same time I get redirected to the page for entering the company name again.

Complete log of the php container: https://pastebin.com/JctSFdd9

**To Reproduce**
1. Setup a fresh install of Twake with the provided docker-compose.yml
2. Create an account
3. create a Company as required

**Comment by RomaricMourgues** [comment]
This is a known and resolved error, I think we have an issue with our docker image update workflow!

[EDIT1] Ok fixed, the workflow is running, I'll tell you when everything is fixed!

**Comment by RomaricMourgues** [comment]
The docker images were updated, the update workflow is working well now 👍
Just update your installation following the update section here: https://doc.twake.app/installation

**Comment by c0ldplasma** [comment]
Thanks for the quick fix :+1:
