### ISSUE TITLE
Problems with deployment of elasticsearch container

### ISSUE THREAD

**Issue by c0ldplasma** [TwakeApp/Twake#102]
(Hopefully this is my last issue for the next days :smile:)
**Describe the bug**
I had two problems with deploying the elasticsearch container with the provided docker-compose.yml. I was able to fix both.

First problem: 
The ./docker-data/es-twake folder by default gets the following permissions: drwxr-xr-x
The elasticsearch container is not able to write inside this folder and throws the following error: https://pastebin.com/ix8b00n3
Executing `chmod 777 ./docker-data/es-twake` fixes that.

Second Problem: 
After I did the chmod 777 and restarted the container I got another error: `[1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]`. After some searching I found that this has to be configured on the host machine. This site explains how to increase it: https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html

No more errors after these two fixes :+1: 

I think this should be included in the documentation.

**Server:**
 - CentOS 7.8 Host

**Comment by RomaricMourgues** [comment]
Hum, it was on the documentation, it is not now 🤔 Some lost information during our transition to Gitbook. Thanks!
I'll update the docs and try to improve our docker-compose too.

**Comment by RomaricMourgues** [comment]
Documentation updated ! 👍
