### ISSUE TITLE
environment.ts has no effect

### ISSUE THREAD

**Issue by c0ldplasma** [TwakeApp/Twake#104]
Today I tried to put my Twake install behind my domain with https. I changed the front_root_url, api_root_url and websocket_url to https://twake.example.com and wss://twake.example.com in the environment.ts config file. Altough the environment.ts gets copied to `/twake-react/src/app/environment` inside the container when it starts, it seems to have no effect. Twake still tries to load content over http.

![Bildschirmfoto vom 2020-07-31 00-00-38](https://user-images.githubusercontent.com/14879514/88979106-44063500-d2c1-11ea-91c3-d4540bd14ab4.png)

**Comment by RomaricMourgues** [comment]
Did you run the command :
docker-compose exec nginx yarn build 
(Just after startup)
The environment change is not yet reloaded on docker up.
We need to improve this because on each Twake update the build will still be necessary.

**Comment by c0ldplasma** [comment]
`docker-compose exec nginx yarn build` did the trick. That info is missing here https://doc.twake.app/configuration and maybe here https://doc.twake.app/configuration/custom-domain-and-https.

**Comment by RomaricMourgues** [comment]
Documentation updated thanks!

**Comment by dichvuhuuich** [comment]
How I know environment.ts working or not? I’ve install on local ok follow by https://doc.twake.app/installation, I want to Custom domain + HTTPS, I follow https://doc.twake.app/configuration/custom-domain-and-https but can not find this folder to edit /etc/nginx/site-enabled/default. I’ve still follow the last doc and my site only go online by mydomain.com:8000 and not https and run very slow. How can I do to put online with Custom domain + HTTPS?

**Comment by RomaricMourgues** [comment]
I wrote a first answer here: https://community.twake.app/t/install-on-local-ok-want-to-custom-domain-https/131/2
