### ISSUE TITLE
Add "Change Twake server" option to the desktop app

### ISSUE THREAD

**Issue by c0ldplasma** [TwakeApp/Twake#105]
**Is your feature request related to a problem? Please describe.**
The desktop app has no option to connect to a self hosted twake instance (or I'm not finding it)

**Describe the solution you'd like**
Add a "Change Twake server" option like in the mobile app

**Comment by RomaricMourgues** [comment]
You can find this option in « Help » -> « Change Twake server » (on the top bar of the Mac version)
On windows I don’t remember where it is, but you should at least have this shortcut :
Ctrl+alt+shift+S
If it works tell me, I’ll update the doc.

**Comment by c0ldplasma** [comment]
On Windows 10 its working flawlessly with Ctrl+alt+shift+S. I have no Mac so I can not test it there.

On Linux (Fedora 32 Gnome 3.36) i can also use the shortcut to open the textfield to enter the server url. After clicking Ok its terminating itself, but not starting again automatically (I have that problem with many apps on Linux so thats probably not a Twake bug). Then after starting it manually again I just get an all white window and its not loading the login page.

**Comment by RomaricMourgues** [comment]
Not good for the Linux version, but I don't have a linux here, on Mac it works well with both shortcut and top menu.
Can you try open the developers tools on linux with ctrl+alt+i ?

**Comment by c0ldplasma** [comment]
The dev tools open neither with ctrl+alt+i nor with ctrl+shift+i. I startet the app with `./twake.appimage --inspect` and its outputting `did-fail-load` every second or so.

**Comment by cheerios911** [comment]
Works great on mac. The "Change Server" settings are in the header unlike the android app where it's on the landing page itself.

<img width="983" alt="Screen Shot 2020-08-11 at 6 05 45 PM" src="https://user-images.githubusercontent.com/69549357/89957574-60796a00-dbfd-11ea-9976-cb5e7e56289d.png">

**Comment by RomaricMourgues** [comment]
Added to the documentation here https://doc.twake.app/how-to-use-it/desktop-and-mobile-app
