### ISSUE TITLE
Workspace icon doesn't work

### ISSUE THREAD

**Issue by jhjacobs81** [TwakeApp/Twake#107]
**Describe the bug**
Whenever i update the workspace settings, and select an icon, it displays in the page itself. But after hitting save, its not updated anywhere, and it goes back to a grey square in the workspace settings as well.

**To Reproduce**
1. Go to 'workspace settings'
2. Click on 'Logo'
3. Click on 'the square to select an image file'
4. The grey square changes into the correct image file

**Expected behavior**
the workspace logo should change into the correct "icon".
**Desktop (please complete the following information):**
 - OS: [iOS/macOS/web]
 - Browser [safari]
 - Version [0]

**Comment by RomaricMourgues** [comment]
Can you show me your docked-compose.yml file ?

**Comment by jhjacobs81** [comment]
its the one that comes from github :) as detailed per: https://doc.twake.app/installation

i tried it again today.. still stuck at the "waiting for shit to get ready" page :(

**Comment by jhjacobs81** [comment]
this was on the saas version by the way.

i am now running the selfhosted version, and there it works nicely 👍

**Comment by x3haloed** [comment]
I’m on the SaaS version, and I’m also having this problem. It also applies to user profile pictures. In fact, nobody in my organization is able to have custom profile photo. Right now, we all have empty/blank profile photos.

**Comment by RomaricMourgues** [comment]
Oh well this is bad news, I’ll fix it soon thanks for the comment!

**Comment by x3haloed** [comment]
No problem. Let me know if there are any further helpful details I can provide. 👍

**Comment by gplutus** [comment]
This still appears to be a problem.  Is there something specific I need to do to fix?

**Comment by RomaricMourgues** [comment]
Are you on-premise or on the SaaS version (web.twake.app) ?

**Comment by gplutus** [comment]
In-premise

**Comment by gplutus** [comment]
In-premise. So it appears that user profile logo updates work, but workspace and company logos do not. Please see the error from./docker-data/logs/nginx/twakeapp_dev_error.log:

Failure to post company logo:
2021/01/06 22:58:24 [error] 11#11: *4694 FastCGI sent in stderr: "PHP message: logo
PHP message: "/tmp/small.jpg"" while reading response header from upstream, client: 172.18.0.1, server: localhost, request: "POST /ajax/workspace/group/data/logo HTTP/1.0", upstream: "fastcgi://172.18.0.7:9000", host: "127.0.0.1:8000"

Successful post of profile logo:
2021/01/06 22:59:24 [error] 11#11: *4710 FastCGI sent in stderr: "PHP message: "/tmp/Window.jpg"" while reading response header from upstream, client: 172.18.0.1, server: localhost, request: "POST /ajax/users/account/identity HTTP/1.0", upstream: "fastcgi://172.18.0.7:9000", host: "127.0.0.1:8000"

It's completely strange, and don't know where to look.
