### ISSUE TITLE
Style support

### ISSUE THREAD

**Issue by jhjacobs81** [TwakeApp/Twake#108]
The current app is nice looking, but a bit too much purple. for more professional use, it would be nice to be able to change the colors to match the company style

**Describe the solution you'd like**
a table added to the database for different color settings. that way it can flow through the diverse clients without having to set the colorscheme on each device/platform differently

**Describe alternatives you've considered**
a preferences option in the client. this would work for most as well. but as someone having a company, i would like to "force" a more universal look and feel.

for company's large and small "looks" are as important as function. Having a small company myself, its very important to let "the brand" shine as much as possible. both to co-workers as well as clients. it also allows guests to recognize more easily which company workplace they are in now, if they use Twake for multiple company's.

**Comment by RomaricMourgues** [comment]
We did start this feature, currently only available from on-premise configuration (https://doc.twake.app/configuration/customisation) and soon available from company preferences :)

**Comment by jhjacobs81** [comment]
ok thanks, then iclose this issue/idea :)
