### ISSUE TITLE
Administration panel

### ISSUE THREAD

**Issue by LawlessWorld** [TwakeApp/Twake#110]
### Describe the question
We've loaded a self-hosted instance of the software and everything seems to be working well.  We weren't sure if there is an administrative section of twake, to manage users, etc.  Did we miss something in the documentation?

**Comment by RomaricMourgues** [comment]
Thanks for using Twake!
Unfortunately there is not administration panel yet available in opensource. It should be available in Q1 2021.
I’m sorry for the inconvenience :/

**Comment by LawlessWorld** [comment]
I imagine with the Linagora purchase it will tie into with openpaas.  

I did see an esn module for twake in openpaas, is that running?  thanks romaric!

**Comment by RomaricMourgues** [comment]
Not yet, we are still thinking of the best way to merge our products. 🙂
