### ISSUE TITLE
Manage channel icons

### ISSUE THREAD

**Issue by jhjacobs81** [TwakeApp/Twake#112]
![image](https://user-images.githubusercontent.com/5583803/89718208-8a444e00-d9bd-11ea-86fa-04bb69408576.png)

It would be nice to be able to add/edit the channel icon. in my case, i set the channel name to "coffeecorner" so it would be nice to add a coffee bean as its icon :)

**Comment by RomaricMourgues** [comment]
Can’t you click on the umbrella and change the icon ?

**Comment by jhjacobs81** [comment]
it seems i can... but when i used the saas version, i could not?

**Comment by RomaricMourgues** [comment]
It seems to work on the SaaS version, I will close this issue for now, feel free to re-open it if it occurs again.
