### ISSUE TITLE
name proposal for the next version

### ISSUE THREAD

**Issue by jhjacobs81** [TwakeApp/Twake#113]
So, the current version is called Albatros.
the next version should be called Puffin!

![puffin](https://user-images.githubusercontent.com/5583803/89718584-f1630200-d9bf-11ea-94f3-513bce5a4abb.jpg)

**Comment by RomaricMourgues** [comment]
Thanks for the idea, but we already have the next version name :)
And moreover we changed our version system for a 2020.Q3.3000 (YEAR.QUARTER.COMMITNUMBER), with a bigger features update on every quarter change.

**Comment by RomaricMourgues** [comment]
(If we don't have idea for next version, we'll take your proposal into account :)
