### ISSUE TITLE
Handler icon to show what is draggable on hover

### ISSUE THREAD

**Issue by BenoitTallandier** [TwakeApp/Twake#12]

**Comment by BenoitTallandier** [comment]
### Problem
Anyone knows that we can drag&drop messages or channel. There is no indication on the interface

### Device
All

### Result expected
Everybody have to know which element is draggable

### Solution / TODO
Have a handle icon on draggable elements

**Comment by RomaricMourgues** [comment]
Here is the next design for messages, note the left grab circle which appear while hovering on the left side of messages.

<img width="1046" alt="Screenshot 2020-07-21 at 11 05 43" src="https://user-images.githubusercontent.com/14353924/88035244-26f39880-cb42-11ea-89da-d85e5c183dcb.png">

**Comment by hantt12** [comment]
Hi @RomaricMourgues , the icon is ok however I have some comments about the drag  and drop feature:

Currently user can use this feature to change a topic into an answer OR move an answer from this topic to another topic

However we are not able to make an answer become a topic. Is that expected?
