### ISSUE TITLE
Desktop app is not draggable

### ISSUE THREAD

**Issue by BenoitTallandier** [TwakeApp/Twake#124]
**Describe the bug**
We can't move desktop app on MacOS

**To Reproduce**
1. Open the app
2. Try to move it

**Expected behavior**
Be able to move Twake app on the desktop.

**Desktop (please complete the following information):**
 - OS: MacOS

**Comment by jhjacobs81** [comment]
yep, same problem here, on Catalina and on Big Sur

**Comment by RomaricMourgues** [comment]
Fixed in next release :)
