### ISSUE TITLE
No "+" button when responding to a message and hard to find how to join a Drive file to the discussion (attachment)

### ISSUE THREAD

**Issue by RomaricMourgues** [TwakeApp/Twake#133]

**Comment by hantt12** [comment]
Hi @RomaricMourgues what do you mean by (+) button?

And what did you do to improve the process of joining a Drive file to a discussion?

**Comment by RomaricMourgues** [comment]
Hello Ha,

On the previous Twake version, if you click on “Answer” there is no “+” button to select a file from computer.
Now you should have every buttons (gif, call, file etc) even in the reply button.

Romaric

**Comment by hantt12** [comment]
Ok it makes sense. Actually now you don't have (+) button but you have icons for attachment/emoji/video call for user to choose, which makes it easier for user. Thanks
