### ISSUE TITLE
User auto complete (ex, channel user)  show every user in Twake

### ISSUE THREAD

**Issue by BenoitTallandier** [TwakeApp/Twake#140]
**Describe the bug**
User auto complete (ex, channel user) show every user in Twake. If I search someone, the input proposition can show users that are not in the workspace

**To Reproduce**
1. Edit channel members
2. Search a user that is signup on Twake and isn't in the workspace

**Desktop (please complete the following information):**
- Desktop & webapp

**Comment by RomaricMourgues** [comment]
For the QA:
- Try to search for an user while creating a new direct conversation or creating a channel,
- Only the users in the current workspace should appear.
