### ISSUE TITLE
channel members autocomplete should match the email prefix address also

### ISSUE THREAD

**Issue by MichaelBailly** [TwakeApp/Twake#145]
I guess the auto complete when adding users on a channel is looking the user name and identifier (@...). IMHO it should also look the email address. Example in the attached video, looking for `dtpham`.

![ezgif-6-0723b7010c43](https://user-images.githubusercontent.com/1465817/91028358-ad960c80-e5fd-11ea-8c55-3f46dfc632a0.gif)

**Comment by RomaricMourgues** [comment]
For the QA:
- Create a user P2 with an username that doesn't match the email.
- Add this user to a workspace where a user P1 is.
- As P1, search for P2 using username or email
Currently we only implement search of the prefix of the mail (so don't try to search with the '@')
