### ISSUE TITLE
CMD + K for user / CTRL+K miss prevent-default

### ISSUE THREAD

**Issue by BenoitTallandier** [TwakeApp/Twake#147]
**Describe the bug**
When looking for discussion on CMD + K, private user discussion don't not appear
And CTRL+K trigger browser quick search in the same time as Twake quick search

**To Reproduce**
1. CMD + K
2. Look for user

**Desktop (please complete the following information):**
Desktop

**Comment by RomaricMourgues** [comment]
For the QA:
- In chrome on linux / window, try the shortcut ctrl+K, only the Twake quick search should open, not the browser quick search.
