### ISSUE TITLE
Reactions for non 4k resolutions

### ISSUE THREAD

**Issue by digitalfredy** [TwakeApp/Twake#157]
**Reactions images are not clear in non 4K (retina) resolutions/screens.**
![twake-reactions](https://user-images.githubusercontent.com/1372919/91081232-c8c04680-e614-11ea-8379-2995d5980a3e.png)

If we take as reference the Hi5 reaction in the center of the screen Twake img is less clear that Mattermost one

**Reactions supposed to be have be clear in most popular resolutions/screens**
I want to do not require an extra visual effort to understand the reaction when using Firefox

**Describe alternatives you've considered**
* Check the emoticons package you are using and compare images (outside the app) with Mattermost emoticons
* Check if it is browser related, does it happen with chrome too? does it happen in the Desktop app? in the Android app....
* Check if in browsers is related with the responsive web design
* Not sure if apply but could we use SVG emoticons to ensure they scale correctly?

**Additional context**
I did not found a way to do this issue private or to remove the image, I realize it will be public after I did the upload. If possible remove the img or tell me how to do it.

**Comment by RomaricMourgues** [comment]
As some of our user don't like our emojis (Emojione v3), I think we can use the Apple set (I thought it was not allowed for usage even in open-source project, but this is the default Mattermost set).
May be use this repo with Apple set: https://github.com/missive/emoji-mart

**Comment by RomaricMourgues** [comment]
For QA: now we are using Apple emojis and emoji-mart emoji picker. We also improved the reaction tag to use a white background.

**Comment by digitalfredy** [comment]
Not sure if related but today I tried to add `:point_up_2:` but is not doing the replacement

**Comment by RomaricMourgues** [comment]
This issue is currently on QA, we changed our emoji selector now it should be perfect :)

**Comment by digitalfredy** [comment]
Hello `:point_up_2:` still not working

**Comment by RomaricMourgues** [comment]
QA close issues but we don’t put things in production right away be patient :)
