### ISSUE TITLE
README broken image link

### ISSUE THREAD

**Issue by Arsnael** [TwakeApp/Twake#159]
**Describe the bug**
The README, that is the vitrine of the code source in Github repo, has a big image link broken. It seems `https://twake.app/medias/features/chat.png` does not exist.

**To Reproduce**
1. Go to README.md on Github
2. Look at the broken image link in your browser

**Expected behavior**
The image should show.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser Firefox
 - Version 79.0

**Comment by RomaricMourgues** [comment]
Fixed thanks :)
