### ISSUE TITLE
Descending messages

### ISSUE THREAD

**Issue by BenoitTallandier** [TwakeApp/Twake#16]
### Problem
When someone replies to a thread too far in the history, we don't know where the message notification came from (we don't know which message was added). You can lose information, and it encourages you to start a new discussion when there is already a block on the topic.

### Device
All 

### Result expected
User should be sure that most recent messages are down in channels.

### Solution / TODO
Groups of messages must be sorted according to the date of the last message in the group.

# User stories
As an user, when I reply to a message that is not in the most recent message block, a system message appears at the very bottom to indicate my reply (like below)
![Capture_decran_2020-09-25_a_16.15.59.png](https://images.zenhubusercontent.com/5f06c5a0e15425885ef10c4a/70c89e6a-ec72-42ae-bc76-63d58aa8fcbf)

**Comment by RomaricMourgues** [comment]
We decided to do this issue only if we have time for the remaining time in Q3.

**Comment by RomaricMourgues** [comment]
We finally decided to do a quick improve, not the final version will be implemented but something that make Messages Thread working at least a little.
- We'll implement a Messenger-like or Mattermost-like system where a notifications of the answered messages will be always visible on the end of the channel. Clicking on it will redirect / open side view to the corresponding thread.

To rediscuss with Benoit:
- May be make messages creation from bottom bar harder to force users to preferably use the "respond" button

**Comment by RomaricMourgues** [comment]
We know this issue is important. So there is an update:
we started working on the issue yesterday and expect to end it in no more than two weeks.
It will fixes several other issues (pagination, threads, scroll etc)
