### ISSUE TITLE
Emoji list is wrong when cleaning filter

### ISSUE THREAD

**Issue by chamerling** [TwakeApp/Twake#185]
**Describe the bug**

After the user cleans the emojione filter, the emojis are not all displayed

**To Reproduce**

1. Open the emojione reaction
2. Type some text to search an emoji
3. Clear the text
4. All the emojis are not displayed

**Expected behavior**

Display all the emojis when clearing text

**Screenshots**

![emojione](https://user-images.githubusercontent.com/264403/91417666-7029bd00-e851-11ea-8b17-62b71d9aa760.gif)

**Desktop (please complete the following information):**
 - OS: OS X
 - Browser Chrome 84

# user story
As a user, when I open emoji picker (edit message reaction for example), I can search "clap" and when I remove "clap" from the search, I can see all emoji as possible.

**Comment by RomaricMourgues** [comment]
Notes for QA: now we are using emoji-mart emoji picker.
