### ISSUE TITLE
Star direct message channel

### ISSUE THREAD

**Issue by BenoitTallandier** [TwakeApp/Twake#209]
**Is your feature request related to a problem? Please describe.**
I talk a lot with someone in direct, It is painfull to go down and look him for in my direct message

**Describe the solution you'd like**
I would love to star this channel with my public and private channel

**Comment by chamerling** [comment]
Isn't it https://github.com/TwakeApp/Twake/issues/203?

**Comment by RomaricMourgues** [comment]
See #310 for original story
