### ISSUE TITLE
channel name not displayed in message when it contains dots

### ISSUE THREAD

**Issue by MichaelBailly** [TwakeApp/Twake#222]
**Describe the bug**
When a channel got dots in its name, the display in a message (using # channel name) does not work.

**To Reproduce**
1. create a channel with dots in its name (twakeapp.com for example)
2.use `#twakeapp.com ` in a message to link to this channel

**Expected behavior**
A display hightlightnin channel object and clickable

**Screenshots**
![image](https://user-images.githubusercontent.com/1465817/92210948-f4062980-ee8f-11ea-9726-12a2d32e1672.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 79

**Comment by RomaricMourgues** [comment]
Related to #223

**Comment by RomaricMourgues** [comment]
For the QA:
- Create a channel with a dot in it,
- Send a message with #... the autocomplete should appear and allow you to send the channel,
- Send the message, the channel should appear in the message, be clickable and have an icon on its left.
