### ISSUE TITLE
Mention fails for some user

### ISSUE THREAD

**Issue by chamerling** [TwakeApp/Twake#223]
**Describe the bug**

In some cases, user can not me mentioned

**To Reproduce**

Check the attached screenshots

![Capture d’écran 2020-09-04 à 09 55 08](https://user-images.githubusercontent.com/264403/92215345-eef7a900-ee94-11ea-84e6-eae0addc742c.png)

![Capture d’écran 2020-09-04 à 09 54 56](https://user-images.githubusercontent.com/264403/92215365-f6b74d80-ee94-11ea-83a5-c1c0400cd427.png)

**Expected behavior**

Use must be able to mention such user

**Screenshots**

**Comment by chamerling** [comment]
Looks like it fails on the whole message when I am mentio
![Capture d’écran 2020-09-04 à 18 05 56](https://user-images.githubusercontent.com/264403/92261363-98f92480-eed9-11ea-9c35-a9d37eefc54b.png)
ned

**Comment by RomaricMourgues** [comment]
For the QA:
- Like in #222 but with users :)
