### ISSUE TITLE
Messages are slow to display when long converation

### ISSUE THREAD

**Issue by RomaricMourgues** [TwakeApp/Twake#234]

**Comment by hantt12** [comment]
hi @RomaricMourgues : How long do you mean? And how fast do you expect?

For example: as a user, I want system to load a conversation of 100 messages successfully in 1 second

Actually the speed varies depending on different factors (implementation, network, server) but at least we can be more specific like: loading 100 messages in a conversation smoothly 

What do you think?

**Comment by RomaricMourgues** [comment]
It is not related to the server response time. It is only a Frontend rendering issue. On the previous version, channels with a lot of messages, answers, formated messages (code, files), were slow (5-10 seconds to display). It should be better now because we only render the visibles messages.

I will give you a way to use the production Backend while using the qa Frontend. Then you’ll be able to check the differences for specific channels.

**Comment by hantt12** [comment]
Yes please guide me to use Production backend with qa frontend

**Comment by hantt12** [comment]
I am able to connect to production backend with QA frontend now

When I try to scroll up to view old messages of a long conversation, it takes pretty long time to load

![20201002_1.png](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/7b5cc6f1-e7ce-48c0-8218-d29911cddbf1)

**Comment by RomaricMourgues** [comment]
Can you give me the network request timing ? There is two possibilities:
- A frontend issue, scroll is not detected and then loading more message from server is not even started or is delayed
- Backend is slow to proceed request

**Comment by hantt12** [comment]
Is this the network request timing you mean?

![20201002_2](https://user-images.githubusercontent.com/53081477/94912886-840cb280-04d2-11eb-8e93-017d63947685.png)

**Comment by RomaricMourgues** [comment]
Yes, this is the procedure:
1 - open a channel
2 - open network and click on the (\) button to clear everything.
3 - select XHR
4 - increase the “Time” column next to Waterfall and keep ordering view by waterfall
5 - send me a video/gif of the loading more message history action

It would be perfect, if you can’t find a way to do this, we can wait for the performances update to check if it works better then.
