### ISSUE TITLE
Mention selector deselect user

### ISSUE THREAD

**Issue by chamerling** [TwakeApp/Twake#242]
**Describe the bug**

Sometimes, the mention selector deselect the user selection. 

**To Reproduce**

- I have several users having `ou` in their names
- Try to mention `ouazana` user by starting to type `@ou`
- The selector is displayed
- Select `Ouazana` user with the keyboard up key
- The UI deselect it and moves down to `Mourgues` user without touching anything from the user point of view
- On the second key up, the `Ouazana` user is selected correctly

This also occurs on message edition.
 
**Expected behavior**

Keep the selected user

**Screenshots**

![bug](https://user-images.githubusercontent.com/264403/92888903-06dfa780-f416-11ea-9630-688ce8c6ee91.gif)

**Desktop (please complete the following information):**

OS X, Chrome 85

**Comment by RomaricMourgues** [comment]
Related to #147

**Comment by stephanevieira75** [comment]
This bug has been fixed since we migrated to antdesign.

I close this issue. :smile:
