### ISSUE TITLE
A better behaviour of the "Load previous messages" button

### ISSUE THREAD

**Issue by huy-ta** [TwakeApp/Twake#251]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when clicking the "Load previous messages" button. It keeps scrolling to the oldest message it can load at a time, which is very annoying.

![image](https://user-images.githubusercontent.com/24670327/93058545-bd9f8a00-f699-11ea-833e-d8c30fd143a7.png)

**Describe the solution you'd like**

The "Load previous messages" button shouldn't change my scroll position so that I can read the messages from the order of newer to older.

**Comment by hantt12** [comment]
Tested in QA frontend with connection to production backend

I  no longer see "Load previous messages" button. Now messages are loaded automatically (it's slow though)

![Peek 2020-10-02 16-04.gif](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/9f5526ee-a3ad-4c5d-a763-46e7b7a4036b)

**Comment by RomaricMourgues** [comment]
I think this is the network, here it’s pretty fast to load old messages (2 seconds was the worst delay I had)…
Yes load-previous messages doesn’t exist, we have an infinite list now, just scrolling should load old messages.

**Comment by RomaricMourgues** [comment]
It is also possible that it is related to performances issues, an issue was already open on this
