### ISSUE TITLE
Can I install the program on my server?

### ISSUE THREAD

**Issue by Forme1234** [TwakeApp/Twake#277]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by RomaricMourgues** [comment]
Yes you can if you are a small/medium team, but you cannot sell it to someone else. If you are a big team or if you want to sell Twake, ask us at contact@twakeapp.com .
The documentation is here: https://doc.twake.app/installation
