### ISSUE TITLE
Allow multiple documents in a single post

### ISSUE THREAD

**Issue by x3haloed** [TwakeApp/Twake#283]
**Is your feature request related to a problem? Please describe.**
I often want to post a collection of files in a channel or a chat together to have a discussion about them together. I get frustrated that I have to post a reply for each file I want to include in a discussion.

**Describe the solution you'd like**
The solution I am proposing is to simply allow users to select multiple files to include in a single post.

**Describe alternatives you've considered**
The alternative I've tried is to post a reply for each file I want to include in the discussion.

**Additional context**
This screenshot shows the UI where I would like multi-select:

![](https://community.twake.app/uploads/default/original/1X/ed2a8703ad849298482f90be5a62d3672863808c.png)

**Comment by hantt12** [comment]
Hi @RomaricMourgues and @stephanevieira75 , user is now able to add multiple files to a single post. 

However, he still have to add the file one by one and repeat the process of clicking attachment icon >> select file source >> select file >> click Select button again and again for files

Can we enhance this process by allowing user to select multiple files at the same time. So the process would be:
- Click attachment icon in message screen
- Select the file source
- Select multiple files (by holding Shift key)
- Click Select button

What do you think?

**Comment by RomaricMourgues** [comment]
Thank you Ha, we did implement the fix but only for the "upload from computer" option (it was already working on Mac OS so thanks for finding the bug!). We will not implement this for the selection of files from the Drive Selector as it take more time and as the Drive will be soon depreciated.

**Comment by stephanevieira75** [comment]
Hello, 

> Hi @RomaricMourgues and @stephanevieira75 , user is now able to add multiple files to a single post.
> 
> However, he still have to add the file one by one and repeat the process of clicking attachment icon >> select file source >> select file >> click Select button again and again for files
> 
> Can we enhance this process by allowing user to select multiple files at the same time. So the process would be:
> 
> * Click attachment icon in message screen
> * Select the file source
> * Select multiple files (by holding Shift key)
> * Click Select button
> 
> What do you think?

Fixed [here](https://github.com/TwakeApp/Twake/pull/410#issue-504206346), thank you Ha ! :+1:
