### ISSUE TITLE
Documentation missing system requirements

### ISSUE THREAD

**Issue by relikd** [TwakeApp/Twake#289]
I've searched your code and documentation and couldn't find any system requirements.  
What are the minimum and recommended specs?

**Comment by RomaricMourgues** [comment]
You are right we didn't add this information into our docs, we will update it.

Currently you'll need at least a 2 cpu + 4 gb of ram machine for 20-50 users depending on their usage and with ElasticSearch disabled.

If you enable ElasticSearch, use two machines, or limit the cpu/ram dedicated to it and use a larger machine (at least 2gb of ram and 1 cpu dedicated to ES for 20-50 users).

If you need to deploy Twake for more users, you can use only one big machine up to 500 users (Will need something like 12 cpu and 32go of ram), then you'll need to use multiple nodes, I will also add information about this in the doc.

**Comment by relikd** [comment]
Thank you :) Will give it a try in the next few days/weeks. Searching for a solution for a small non-profit team, with 10-15 people. Would be nice if the docs show multiple scenarios for different group sizes like you said in your comment 👍

**Comment by lurcheous** [comment]
Do you have instructions for building on Debian as Docker breaches company policies. rather build on VM or bare metal?

**Comment by RomaricMourgues** [comment]
No we don't have this documentation yet.
It should not be too difficult to do, the main part is for the PHP part, there is a lot of things to install.
You will find everything you need here: https://github.com/TwakeApp/Twake/tree/main/twake/docker
