### ISSUE TITLE
Scroll bars on Windows

### ISSUE THREAD

**Issue by bluffitee** [TwakeApp/Twake#302]
**Describe the bug**
Scroll bars are always on even if there are no items on list. This makes the UI look terrible on Windows devices. A possible fix could be to just set overflow property to auto, and to customize the look of the scroll bar so it doesn't look that terrible. It's just a huge turn off design-wise.

**To Reproduce**
No steps to follow. Just open a board and they are there.

**Expected behavior**
Scroll bars shouldn't exist when the list isn't that long. When they do, they are pretty ugly on Windows.

**Screenshots**
![screenshot](https://raw.githubusercontent.com/bluffitee/twk-img/master/twake.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version 80

**Comment by tlle14** [comment]
Retest pass on Chrome, Firefox, and Edge browser on Windows
- The scrolling doesn't appear when there's an empty board
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/bda8b04a-890a-49e0-934c-4e251e682c57)

- The scrolling display for the long list cannot display all on the window
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/852b9fb7-6e38-4faa-bf23-ef17911682a9)
