### ISSUE TITLE
[Story] View Channel in my sidebar

### ISSUE THREAD

**Issue by BenoitTallandier** [TwakeApp/Twake#309]
EPIC #308 

** As an internal user, I can see the channels (public or private) in my workspace that I am a member of in the sidebar. **
![Capture d’écran 2020-10-05 à 10.57.20.png](https://images.zenhubusercontent.com/5f06c5a0e15425885ef10c4a/c60f6317-7810-41f5-b5e6-32451a7b07b4)

**Comment by tlle14** [comment]
Retest pass!
User is able to see the channel list in the workspace.

![image](https://user-images.githubusercontent.com/69950655/106125190-6c96bb00-618e-11eb-8851-f533765c858c.png)
