### ISSUE TITLE
[Story] Mention notification

### ISSUE THREAD

**Issue by BenoitTallandier** [TwakeApp/Twake#354]
Epic #350

**As a user, I receive a specific notification when I am mentioned**

**Comment by iFloris** [comment]
Yeah, I think this would be very helpful, especially in situations where people are working asynchronous, such as in different timezones, on different workdays or perhaps even different working hours (during the day or during the evening/night).

Right now, a user only sees that he/she was part of a conversation after having logged in I think.
We tested this a bit, and I think Twake only sends an email for newly created accounts and nothing else.

**Comment by BenoitTallandier** [comment]
We'll be done in the Epic #350
