### ISSUE TITLE
Add TypeORM in the node backend

### ISSUE THREAD

**Issue by chamerling** [TwakeApp/Twake#362]
1. Create the platform service and integrate https://typeorm.io/#/.
2. Bootstrap some entities in channels service

**Comment by RomaricMourgues** [comment]
Can you also prepare a separated services for the driver ? Do not expose directly the TypeORM ?
I will need:
- a "connect" method that define and start connexion to the database
- a "getDriver" method that returns my modified driver
- a "getRepository" method that returns my modified repository.
Of course you can implement the default TypeORM in this middleware for now.

I also need to change the parameters for the database driver, there is already parameters needed for TypeORM but we'll need more options, so please create a middleware for the driver's option typing.

And remember, we will use MongoDB by default until we have the Cassandra adapter.

**Comment by chamerling** [comment]
Of course, this is what I planned to do.
