### ISSUE TITLE
Popup window not disappearing

### ISSUE THREAD

**Issue by droste89** [TwakeApp/Twake#37]
**Describe the bug**
When pressing Enter to confirm the suppression of a workspace, the popup message doesn't disappear. However, the suppression of the workspace is effective.

**To Reproduce**
1. Go to 'Workspace settings'
2. Click on 'Delete Workspace'
3. Enter the name of the workspace
4. Click on 'Delete'
5. Press Enter to confirm
6. See error

**Expected behavior**
The popup message disappears when pressing enter.

**Screenshots**
![Capture d’écran de 2020-07-17 15-29-22](https://user-images.githubusercontent.com/68430672/87791329-5d7b9b80-c842-11ea-8e72-3e0196dc2fde.png)

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu
 - Browser: Firefox
 - Version: 67.0

**Additional context**
None

**Comment by RomaricMourgues** [comment]
Hi, thanks, it should be fixed in the next release #36
