### ISSUE TITLE
No calendar or tasks in Saas version

### ISSUE THREAD

**Issue by outlawservices** [TwakeApp/Twake#385]
**Describe the bug**
I've created an account and in searching the applications there is no Task or calendar option for me.  I was able to find the documents plugin, but the others seem to have disappeared.

**To Reproduce**
1. create new account
2. go to workspace settings
3. search connectors
4. you will find documents, but no able to search for calendar or tasks

**Expected behavior**
I'd like to have tasks lol

**Comment by RomaricMourgues** [comment]
Hi, you can search for apps in the workspace parameters.
We fixed the default app not being added to new worksapces, thanks for spotting it!
