### ISSUE TITLE
File upload does not work on new install

### ISSUE THREAD

**Issue by ianhyzy** [TwakeApp/Twake#41]
**Describe the bug**
Uploading files doesn't appear to work correctly on a fresh install of Twake.

**To Reproduce**
1. Install Twake
2. Click Documents
3. Click "Import from the computer"
4. progress bar will show upload but file will not appear in Main
3a. Create a new folder
3b. Navigate into the folder and upload a file from computer
3c. File appears as a list item but cannot be previewed or downloaded

**Expected behavior**
Files should appear with an icon or preview and download correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/3400872/87883232-a317a000-c9cb-11ea-8dbe-5498ad8bc5ce.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 84.0.4147.89

**Additional context**
Fresh install on Ubuntu 20 with latest docker version.

**Comment by RomaricMourgues** [comment]
Can you try with the latest docker-compose.yml.dist from the main branch ? We just updated the dockers so you just have to
- Get the latest docker-compose (two volumes added)
- stop your containers
- docker-compose pull
- start everything again
