### ISSUE TITLE
a few english translation fixes

### ISSUE THREAD

**Issue by ianhyzy** [TwakeApp/Twake#42]
**Describe the bug**
A few of the english translations seem off:

1. Calendar should say "to":
![image](https://user-images.githubusercontent.com/3400872/87883328-351fa880-c9cc-11ea-8970-87959ee2cfac.png)

2. "Import from the computer" is technically correct but clunky, "Import from computer" is more natural
![image](https://user-images.githubusercontent.com/3400872/87883335-4b2d6900-c9cc-11ea-8a17-e57122bf333a.png)

3. "Maximum weight" should say "Maximum (file) size 5 mb"
![image](https://user-images.githubusercontent.com/3400872/87883404-c55ded80-c9cc-11ea-9ea6-3486db97cb77.png)

**Comment by BenoitTallandier** [comment]
Hi @ianhyzy 
Thank you for your return! We'll change that 🙏

**Comment by RomaricMourgues** [comment]
Hi, we just fixed this issue. It should be available in a few days on the docker image and it is already available on github (you must use volumes to Twake code in this case).
