### ISSUE TITLE
Drag and drop bug not opening editor

### ISSUE THREAD

**Issue by RomaricMourgues** [TwakeApp/Twake#423]
Drag and drop bug not opening editor

**Comment by hantt12** [comment]
Hi Romaric, could you  please give me more details on how to reproduce this bug?

**Comment by RomaricMourgues** [comment]
Hi sorry yes, so we want to open the inputs while we drag-drop a file over the discussion threads to be able to see the files uploaded in over the right input.

**Comment by hantt12** [comment]
But I am not able to drop file to discussion?
![Peek 2020-10-29 15-16.gif](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/01dc4d20-fc16-40f9-94de-9007dd1ab189)

**Comment by RomaricMourgues** [comment]
Oh, were you ever able to drag drop a file? Because here everybody is able to drag-drop files to threads, that is strange!

**Comment by hantt12** [comment]
I don't think I have ever done that before

**Comment by RomaricMourgues** [comment]
Can you try this ? https://css-tricks.com/examples/DragAndDropFileUploading/

**Comment by hantt12** [comment]
It does not work for me 

I tested the following browsers on Ubuntu:
Chrome Version 86.0.4240.111 (Official Build) (64-bit)
Firefox 82.0 (64-bit)

**Comment by RomaricMourgues** [comment]
Have you any web application that allows you to do drag and drop?

**Comment by hantt12** [comment]
I tried some other web applications. Apparently it does not work for me. I will try some other computers with the same Ubuntu version and keep you updated

**Comment by hantt12** [comment]
HI Romaric, somehow the problem happens on my PC only (I tried with other PC with the same Ubuntu/Chrome/Firefox version). 

As I check this backlog in other PC, I will move this to Passed QA column
