### ISSUE TITLE
Thread view messages should not display button to display thread view

### ISSUE THREAD

**Issue by chamerling** [TwakeApp/Twake#444]
1. Open a thread by clicking on the message button arrow
2. When on the thread, the message button arrow is still displayed, clicking on it does nothing

The 'message button arrow' is this one

![Capture d’écran 2020-10-22 à 08 54 07](https://user-images.githubusercontent.com/264403/96835724-40a7c300-1444-11eb-9210-4e9466ff6b2c.png)

Expected: 

When on a thread, do not display the button

**Comment by tlle14** [comment]
Thank @stephanevieira75 
Retest pass
![Peek 2021-01-27 17-51.gif](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/796acf3f-1ff8-49dd-9033-af0233d45576)

The button "thread view" doesn't display on the thread view anymore. 
Tested on:
- Ubuntu: Chrome, Firefox
- Windows: Chrome, Firefox, Edge
