### ISSUE TITLE
Smooth display of options on mouse over message

### ISSUE THREAD

**Issue by chamerling** [TwakeApp/Twake#445]
On the UX side, it will be nice to add some fade when message options are displayed/hidden on mouse hover:

Talking about the move message on the left, and message options on the right.

![Capture d’écran 2020-10-22 à 09 36 49](https://user-images.githubusercontent.com/264403/96839974-2b359780-144a-11eb-9124-73cc91ab191b.png)

Take a look on Notion.io for example, there is a quick fade, and even if very short, it really add some "comfort".

**Comment by hantt12** [comment]
Hi Christophe, could you please give me more details on this improvement?

**Comment by RomaricMourgues** [comment]
The options where appearing instantaneously before on mouse over. Now we should have a quick fade animation.
