### ISSUE TITLE
Need more information in order to process socket events

### ISSUE THREAD

**Issue by RomaricMourgues** [TwakeApp/Twake#462]
I need more information in order to process socket events.

Currently I join a websocket room by its name, for instance "/channels". But then when I receive events here is what I have:

```
{
  action: "created"
  path: "/channels/5f93083340c26f00613a3b9e"
  resource: {name: "name_1603471411", id: "5f93083340c26f00613a3b9e"}
  type: "channel"
}
```

I need the room name in order to dispatch the event to the correct collection on Frontend.

**Comment by chamerling** [comment]
@RomaricMourgues I am on it!
