### ISSUE TITLE
[Patch Q3.107] Drive public sharing is not working 

### ISSUE THREAD

**Issue by BenoitTallandier** [TwakeApp/Twake#479]
**Describe the bug**
I can't open a public link from the drive. "No 'Access-Control-Allow-Origin'".
The response of "drive/v2/get" is "{"status":"error","_cookies":[]}".

**To Reproduce**
1. Create a folder
2. Put something in it
3. Create a public link on this folder
4. Try to open it in private windows

**Comment by hantt12** [comment]
System shows message: "This public link is invalid or has expired."
![2020-11-16_14-46.png](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/88128632-5e90-4b19-bb12-a9abfa4b92ae)

**Comment by RomaricMourgues** [comment]
Oh thanks! We are fixing this today I hope to put the whole update on production this week.
I keep you updated.

**Comment by RomaricMourgues** [comment]
Fixed ! :)
