### ISSUE TITLE
Last message fade looks bad

### ISSUE THREAD

**Issue by chamerling** [TwakeApp/Twake#484]
When someone post a new message in a thread and when it is displayed in the main view, it looks bad. 
Fade is nice when scrolling but when displaying a message at the bottom like this one, it hides too much text:

![Capture d’écran 2020-10-29 à 11 27 46](https://user-images.githubusercontent.com/264403/97556515-e4abe400-19d9-11eb-8fa6-986aba8125a4.png)

**Comment by chamerling** [comment]
Also got this, while using message composer

![Capture d’écran 2020-10-29 à 16 45 42](https://user-images.githubusercontent.com/264403/97597788-83e6d080-1a06-11eb-9dd3-2697c8769693.png)

**Comment by RomaricMourgues** [comment]
Fixed on Q4
