### ISSUE TITLE
[Patch Q3.dev] Implement JWT for frontend dev on Q4

### ISSUE THREAD

**Issue by RomaricMourgues** [TwakeApp/Twake#558]
**QA:** can you check that login, password recovery and account creation still work ?

**Comment by hantt12** [comment]
Hi @RomaricMourgues there is something wrong with account creation process. 
It takes super long after adding collaborators. System keeps show blank screen for about 10 minutes. Even though the next screen is shown after all but to user it is completely not good

![Peek 2020-11-17 11-19.gif](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/41b7b0f6-44a5-45fe-b070-2750b2bdc6df)

**Comment by RomaricMourgues** [comment]
Thanks I patch it today or tomorrow :)

**Comment by RomaricMourgues** [comment]
Fixed :)
