### ISSUE TITLE
email déjà utilisé, mais n'existe pas

### ISSUE THREAD

**Issue by scenaristeur** [TwakeApp/Twake#630]
Bonjour, en testant la platforme web, je suis confronté à ce problème.

Mon email serait déjà utilisé donc je ne peux m'inscrire, et lorsque je demande un autre mot de passe, mon email n'existe pas ???
![Capture d’écran du 2020-12-06 12-17-58](https://user-images.githubusercontent.com/4020744/101278838-656eb480-37be-11eb-8edb-6c5c92c5feb7.png)
![Capture d’écran du 2020-12-06 12-18-33](https://user-images.githubusercontent.com/4020744/101278840-66074b00-37be-11eb-9d0a-fa75ff2387d5.png)

**Comment by RomaricMourgues** [comment]
Bonjour, pouvez-vous tenter avec un autre nom d'utilisateur ? Nous avons récemment corrigé une erreur relative au message d'erreur qui affiche email utilisé au lieu de nom d'utilisateur utilisé.
La correction sera en production dans quelques jours

**Comment by scenaristeur** [comment]
Bonjour, 
@RomaricMourgues , effectivement ça passe si je mets comme utilisateur 'dgdflkjhlsdfkhblojbdsoljbsds' qui ne doit pas avoir été déjà utilisé ;-). merci
