### ISSUE TITLE
Stuck on Waiting for DB to start...

### ISSUE THREAD

**Issue by PeterXQChen** [TwakeApp/Twake#649]
**Describe the bug**
Frontend stuck on "Waiting for DB to start..." Waiting over 10 minutes does not fix the issue either.

**To Reproduce**
1. Pull the latest dockerimage
2. run docker-composer up -d
3. Look at docker logs and get constant ScyllaDB not found errors

**Expected behavior**
Start the application and be on the login screen

**Screenshots**
Frontend: https://i.imgur.com/T1VMdvM.jpg
Docker log: https://i.imgur.com/PXOvLZn.jpg

**Desktop (please complete the following information):**
CentOS 7 - Fresh install with fresh docker install
![1](https://user-images.githubusercontent.com/419976/101591457-96b3d400-39ba-11eb-8842-942c67e48619.jpg)
![2](https://user-images.githubusercontent.com/419976/101591458-974c6a80-39ba-11eb-9f4d-3e866960a6ce.jpg)

**Comment by psyhlo** [comment]
same here
several times restart the containers and remove, and recreate
still waiting after 12 hours

**Comment by RomaricMourgues** [comment]
Hello, this issue appear unfortunately on some machines with specific OS or low Ram/CPU. Please see if ScyllaDB was able to startup with:
`docker-compose logs -f --tail 100 scylladb`
We are working on connectors to be able to run using mongodb for small and medium deployment :)

**Comment by sineasfog** [comment]
Hi,[Setting the sysctl parameter aio-max-nr value to 1048576](https://sort.veritas.com/public/documents/HSO/2.0/linux/productguides/html/hfo_admin_rhel/ch04s03.htm) on the host seems to solve this issue for now.
```
# /etc/sysctl.conf
fs.aio-max-nr = 1048576

# Activate settings
sysctl -p /etc/sysctl.conf
```

**Comment by PeterXQChen** [comment]
Seems like it couldnt start due to being unable to connect to the storage service?

![image](https://user-images.githubusercontent.com/419976/101649538-00f36580-3a09-11eb-9232-1d4fc3520d4d.png)

**Comment by RomaricMourgues** [comment]
The issues is actually related to your CPU architecture:
"scylla requires the sse4.2 and clmul [...]"
We can continue this discussion here (I dont know if this is you on the topic too :) )
https://community.twake.app/t/is-it-possible-to-run-twake-without-pclmul-support/118

**Comment by PeterXQChen** [comment]
No thats not me but that answers the question.

I'll try on another server with newer hardware. Hopefully the version with MongoDB becomes available and is a seamless switch over.

Thanks!

**Comment by bananaspliff** [comment]
+1 for mongo
