### ISSUE TITLE
Big file upload

### ISSUE THREAD

**Issue by BenoitTallandier** [TwakeApp/Twake#65]
**Describe the bug**
When user upload big file and download it, the file is empty (0ko)

**To Reproduce**
1. Upload big file (1go)
2. Download it

**Expected behavior**
A possibility to upload and download big file

**Desktop (please complete the following information):**
 - OS: *
 - Browser *

**Comment by RomaricMourgues** [comment]
I found the origin of the issue, we store file sizes in int32, so we are limited to 2Go files... It's a dumb issue but we cannot switch from int32 to bigint in scylladb, I'll find an other way!
