### ISSUE TITLE
After Docker installation - Email already in use

### ISSUE THREAD

**Issue by sokratesli** [TwakeApp/Twake#650]
**Describe the bug**
I installed the docker Twake on a local ubunut 18.04 vm 
It seems to work => Twake is starting up under port 8000
my next stepp is to create a new user (is that correct?)
I add a new user with the expected credantials and get an error "the email es alredy in use" - but how is that possible?

I tried to reinstall Twake several times (incl. new vm) with the same error at the end

**Expected behavior**
What can I do? What did I miss?

Thank you for you help

**Comment by RomaricMourgues** [comment]
Hello @sokratesli , this is not in the documentation but you cannot use the usernames with less than 4 characters and also the usernames: guest, admin, all, here, null or undefined
We have a second issue with the displayed error, this is why it talks about your email.
Romaric
