### ISSUE TITLE
Add "provider" column for files to determinate where their are stored (preparation for OVH migration)

### ISSUE THREAD

**Issue by RomaricMourgues** [TwakeApp/Twake#754]

**Comment by gplutus** [comment]
Just a suggestion, but perhaps it would be better to create a "Location" sub-menu under the "Move" option in the file's context menu?  As opposed to cluttering the interface?

![image](https://user-images.githubusercontent.com/36609341/105797493-4f26de80-5f4d-11eb-9c9b-97e2d56c2949.png)
