### ISSUE TITLE
Data in 2 different accounts is messed up because of cache issue

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Twake#804]
# Actual Result
Because of cache, it displays some channels of the already-logged-out-user on the channel list of the current user. 

On Web:
![image](https://user-images.githubusercontent.com/69950655/105280643-cc182800-5bdc-11eb-967c-9bc0cfb65306.png)

On Mobile:
![image](https://user-images.githubusercontent.com/69950655/105280931-91fb5600-5bdd-11eb-8157-4e2417efbfe8.png)

# Expected Result
The cache should be cleared when user logged out

# Environment
Firefox
Beta version

**Comment by RomaricMourgues** [comment]
Thanks we are on it!
