### ISSUE TITLE
Edit Channel > A member is able to edit a channel created by another user

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Twake#842]
# Precondition
Story: https://github.com/TwakeApp/Twake/issues/512

# Actual Result
A member is able to edit a channel name/ description that is created by another user
![Peek 2021-01-29 10-06.gif](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/1ea55daf-1ade-48bc-807d-eab66e7c9efe)

# Expected Result
The channel should be able to be edited by a workspace admin or a channel creator only. 

>When I look to edit a channel
And I am a workspace admin Or the channel creator

# Environment
Chrome Ubuntu
QA testing environment

**Comment by RomaricMourgues** [comment]
Now only destructive actions reserved to administrators and creators. Every others actions are available to every members except guests.

**Comment by tlle14** [comment]
Thank @RomaricMourgues 
Please update the story with a detailed explanation.
