### ISSUE TITLE
Page refresh and routing problem when saving account settings

### ISSUE THREAD

**Issue by Dahpril** [TwakeApp/Twake#87]
**Describe the bug**
I noticed a bug which happens when trying to change some account settings, but not everytime !

When clicking on save button, page refresh and settings aren’t saved. Browser console giving `JSON.parse : unexpected end of data` error, and ajax call to /ajax/users/account/identity/ don’t respond anything.

Checking docker-compose logs, I saw this error :

`Pecee\SimpleRouter\Exceptions\NotFoundHttpException: Route "/ajax/users/account/identity/" or method "get" not allowed. in /twake-core/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php:415`

If I attempt to edit multiple times, it eventually works after 4 of 5 retries. Sometimes, before page refreshing (which seems to be not a normal behavior), I can glimpse for a second a red error message, but can’t read it.

**Steps to Reproduce**
1. Go to 'Account settings'
2. Try to change any setting, except languages options
3. Page will refresh and setting will not be saved
4. See error in docker-compose logs

**Expected behavior**
Page should not reload and setting should be saved

**Desktop:**
 - OS: Windows 10 2004
 - Browser: Firefox 78.0.2

**Additional Context**
Doesn't occurs on Chrome 84.0.4147.89 nor on Opera 69.0.3686.77

Thanks 🙂 !

**Comment by RomaricMourgues** [comment]
When you have time @stephanevieira75 can you investigate this one ?

**Comment by stephanevieira75** [comment]
Hello, this issue is fixed [here](https://github.com/TwakeApp/Twake/pull/141) ! :smile: 

Missing `href` attribute in link makes refreshing the page in Firefox.
