### ISSUE TITLE
Error when editing event dates

### ISSUE THREAD

**Issue by RomaricMourgues** [TwakeApp/Twake#96]
**Describe the bug**
I was creating an event in the calendar, I edited the start date, then the end date (which was not updating) and boom:
TypeError: this.sources[e] is undefined

**To Reproduce**
1. Go to Calendar and create event
2. Edit start date, end date
3. See error

**Context**
This is not happening after reloading app, so may be related to #27

**Comment by krishnanunnir** [comment]
Great work guys, this looks amazing, I wanted to contribute to the project, would it be okay if I work on this?

**Comment by RomaricMourgues** [comment]
Of course! Our documentation is very young, but you can find how to start the development server here:
https://doc.twake.app/internal-documentation/get_started
Tell me if it doesn't works or if the documentation is unclear :)

By the way, I tried to reproduce the error but it seems I don't have it on my side, so it needs more investigation...

**Comment by krishnanunnir** [comment]
Thanks! I will have a look around.
Also the link for mac dmg seems to be broken. Please have a look.

**Comment by RomaricMourgues** [comment]
Just fixed, we were fixing it :)

**Comment by RomaricMourgues** [comment]
Not able to reproduce, and was probably related to #27, closing until somebody have the error again.
