### ISSUE TITLE
High CPU usage in idle

### ISSUE THREAD

**Issue by c0ldplasma** [TwakeApp/Twake#97]
I setup Twake with the default docker-compose.yml. I noticed that the php and the scylladb container have very high idle CPU usage. The php container idles at around 75% while the scylladb container idles at 52% (docker stats). 

I already found out that its normal for scylladb to use a lot of CPU and I was able to reduce the usage of the scylladb container to around 35% with the `--smp 1` command line argument.

Is it also possible to reduce the idle CPU usage of the php container?

**Comment by RomaricMourgues** [comment]
We configured the php-fpm node in static mode for a machine of 2Go RAM + 2vcpu. It suits our needs in SaaS mode but I understand it should be editable.
The file is here: https://github.com/TwakeApp/Twake/blob/main/twake/docker/twake-php/www.conf

In the meanwhile, a quick fix could be:
1. in docker-compose.yml add a volume to php container from ./docker-data/fpm-config/www.conf to /usr/local/etc/php-fpm.d/www.conf
2. edit ./docker-data/fpm-config/www.conf with better parameters (see bellow).
3. run `docker-compose up`

Better performances parameters:
```
[www]

user = www-data
group = www-data

listen = /run/php/php7.0-fpm.sock

listen.owner = www-data
listen.group = www-data

; ondemand should be better suited for your need
pm = ondemand
pm.max_children = 30
pm.process_idle_timeout = 10s
pm.max_requests = 100

catch_workers_output = yes
php_flag[display_errors] = on
php_admin_value[error_log] = /var/log/fpm-php.www.log
php_admin_flag[log_errors] = on
```

Tell me if it works,
thanks for testing Twake! 🥳

**Comment by c0ldplasma** [comment]
Thanks for the quick reply. I tried changing the www.conf like you suggested. The memory usage decreased significantly, but the CPU usage still is at 75%. 

I executed `ps xuww` inside the container and found the process causing it:
`root      2358 70.8 0.1 546536 30664 ?        Rl   17:34   0:06 php bin/console twake:scheduled_notifications_consume_timetable`

**Comment by RomaricMourgues** [comment]
Interesting, what did you do in Twake currently ? Did you add events or tasks ?

I think we may need to add a sleep in the loops in the method consumeShards from https://github.com/TwakeApp/Twake/blob/main/twake/backend/core/src/Twake/Core/Services/Queues/Scheduled.php

If you never done anything on Twake, may be the loop has nothing to read and is too fast, I'll wait for your response.

**Comment by c0ldplasma** [comment]
Its a completely fresh install. So far I haven't even created an account.

Indeed the consumeShards method ran through extremely fast, so I put a 100ms sleep in the while loop in https://github.com/TwakeApp/Twake/blob/main/twake/backend/core/src/Twake/Core/Command/ScheduledNotificationsConsumeTimetable.php so it gets called less. This fixed the high CPU usage, but I don't know if/how this affects functionalty of Twake.

Meanwhile I setup an SMTP server so I could try creating an account and a company, but ran into a php error. I'm creating a new issue for that.

**Comment by RomaricMourgues** [comment]
It shouldn't affect Twake, it's a bug it should be their from the begining, thank for testing the fix!
If you have time you can propose the change via a Pull Request, else I will do it in the next weeks (team on hollydays 🙂 )

You can create account without SMTP, the default configuration has not email verification.
Thanks for your time!

**Comment by RomaricMourgues** [comment]
Thanks c0ldplasma for the PR!
